server:
  port: 5000
spring:
  datasource:
    url: ${DB_URL}
    username: postgres
    password: docker
  jpa:
    database:
      platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            no_contextual_content: true
app:
  version: 1.0.0